name: Build System Graph as README.graph.jsonl

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.233.0
        with:
          ruby-version: 3.2.8
      - name: Setup Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
      - name: Make Graphs from Annotations
        run: ruby doxref.rb
      - name: Make Diagrams from Graphs
        run: cat README.graph.jsonl | ruby makesvg.rb
      - name: Checkin Graphs and Diagrams
        run: |
          git config --global user.email "ward@c2.com"
          git config --global user.name "Ward Cunningham"
          git add README.graph.jsonl
          git add graphs/*.svg
          if git diff --cached --exit-code >/dev/null
            then
              echo no graph changes
            else
              git commit -m '-- graph action --'
              git push origin ${GITHUB_REF_NAME}
          fi
